### ISSUE TITLE
Get TPS as placeholder

### ISSUE THREAD

**Issue by TrevorSayre** [Puharesource/TitleManager#106]
I would like to display the server TPS in the tab menu. This could require the /tps command permission similar to how vault and bungeecord are required for certain current placeholders?

%{tps} should give the exact output of /tps
e.g. &6TPS from last 1m, 5m, 15m: &a19.96, 19.97, 19.98

Optionally %{tps-data} could give just the numbers (so you could color them how you like)
e.g. 19.96, 19.97, 19.98

Optionally %{tps-text} could give just the text (so you could color them how you like)
e.g. TPS from last 1m, 5m, 15m:

Optionally %{tps-1} could give jus the tps from the last 1m
Optionally %{tps-5} could give jus the tps from the last 5m
Optionally %{tps-15} could give jus the tps from the last 15m

Alternatively, is it possible to get a command output for a script?

**Comment by Puharesource** [comment]
Spigot / Bukkit doesn't allow you to get the TPS, so the only way this would be possible, would be to calculate this myself, which I'd rather not do for a plugin like TitleManager.

You did however give me a very fun challenge, to see if I can somehow allow scripts to get a command's output. I'll see what I can do 👍 .

**Comment by Puharesource** [comment]
Here's a little sneak peak 😜 
![TPS Placeholder](https://i.puha.io/170124011624.png)

The syntax will be as follows: `${tps:[fade-in;stay;fade-out]FULL|SHORT|1|5|15}`  
[`fade-in`;`stay`;`fade-out`] is completely optional.  
`FULL` Will show the entire output of the `/tps` command.
`SHORT` Will show all three TPS's similar to the sneak peak.
`1` Will show the last minute's TPS.
`5` Will show the last 5 minutes' TPS.
`15` Will show the last 15 minutes' TPS.

**Comment by Puharesource** [comment]
Now I don't know how big your server is, but could you please test the latest commit's (0a6df13dfd44a0ed9e4aa18d513ffae58883f9a7) build out on a production server? (While using the TPS script of course).

This is how to build the project:
1.1 (Linux / OSX) Run `./gradlew build` in the root directory of the project.
1.2 (Windows) Run `gradlew.bat build` in the root directory of your project.
2. You'll find the output build in the directory `out/`

**Comment by TrevorSayre** [comment]
I have a test server I can run it on, no problem. Will report back when I get the chance. Thank you for your efforts!

**Comment by SrLeojaco** [comment]
![image](https://user-images.githubusercontent.com/16531305/60296209-e6692180-9925-11e9-8574-3422e1711ed8.png)


Hey!

I was trying to make it but it shows the "Tps from last 1m, 5m, 15m..." which is too alrge...


Im using
  - '%{tps:SHORT|1|5}'

**Comment by Puharesource** [comment]
@SrLeojaco You can't show multiple things inside the same placeholders, you'll have to do this yourself like this: `%{tps:1}, %{tps:5}` if you want to show 1 minute and 5 minutes.

**Comment by SrLeojaco** [comment]
@Puharesource i'm getting on console 10/minute this error

`[00:05:53] [pool-19-thread-1/ERROR]: Command Dispatched Async: tps
[00:05:53] [pool-19-thread-1/ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.8.9.jar:git-TacoSpigot-"27784328"]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:596) [spigot-1.8.9.jar:git-TacoSpigot-"27784328"]
	at io.puharesource.mc.titlemanager.placeholder.PlaceholderTps.getOutput(PlaceholderTps.kt:11) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.placeholder.PlaceholderTps.getTps(PlaceholderTps.kt:17) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerPlaceholders$14.invoke(TitleManagerPlugin.kt:557) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerPlaceholders$14.invoke(TitleManagerPlugin.kt:47) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:160) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.APIProvider.setScoreboardValueWithPlaceholders(APIProvider.kt:611) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setScoreboardValueWithPlaceholders(TitleManagerPlugin.kt) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setScoreboardValue(PlayerExtensions.kt:170) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:367) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:46) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:81) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:88) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:11) [TitleManager-2.1.2.jar:?]
	at io.puharesource.mc.titlemanager.scheduling.AsyncScheduler$scheduleRaw$1.run(AsyncScheduler.kt:43) [TitleManager-2.1.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_72]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by computercrazy77** [comment]
Hello!
Is there a way I can change the color of the tps output? I'm using it in my player list.
`&8TPS &f%{tps:1}` is what I have, but the tps output is not white.
