### ISSUE TITLE
Error when players log in

### ISSUE THREAD

**Issue by BobKyle** [Puharesource/TitleManager#114]
I get an error in the console when a player logs in, as well as when I try to use /tm abroadcast. Rest of the plugin works fine, but I can't produce an actionbar announcement.

Below is what comes up when a player logs in:
```2:44:15 PM CONSOLE: Birchaw has logged in.
2:44:15 PM CONSOLE: [INFO] Birchaw[/86.149.106.239:62443] logged in with entity id 179312 at ([Eros]5747.062948010998, 72.0, 3965.243037318573)
2:44:16 PM CONSOLE: WARN]: Exception in thread "RxComputationScheduler-1"
2:44:16 PM CONSOLE: WARN]: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
2:44:16 PM CONSOLE: WARN]: at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2:44:16 PM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)
2:44:16 PM CONSOLE: WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.APIProvider.sendActionbar(APIProvider.kt:565)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.APIProvider.sendActionbarWithPlaceholders(APIProvider.kt:586)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendActionbarWithPlaceholders(TitleManagerPlugin.kt:683)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendActionbar(PlayerExtensions.kt:54)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$3.invoke(TitleManagerPlugin.kt:402)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:488)
2:44:16 PM CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:44)
2:44:16 PM CONSOLE: WARN]: at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
2:44:16 PM CONSOLE: WARN]: at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
2:44:16 PM CONSOLE: WARN]: at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
2:44:16 PM CONSOLE: WARN]: at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
2:44:16 PM CONSOLE: WARN]: at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
2:44:16 PM CONSOLE: WARN]: at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
2:44:16 PM CONSOLE: WARN]: ... 7 more
```

**Comment by Puharesource** [comment]
What version of Minecraft is your server running on?

**Comment by BobKyle** [comment]
1.11.2

**Comment by Puharesource** [comment]
Are you not running Spigot then? It uses the Spigot API to display actionbar messages, so if you're just running CraftBukkit, then the plugin won't work with Actionbar messages.

**Comment by BobKyle** [comment]
Should be running the latest Spigot

**Comment by BobKyle** [comment]
This is what shows when I use /tm abroadcast, should have included this.

`3:10:02 PM CONSOLE: [INFO] Birchaw issued server command: /tm abroadcast Are you seeing something from this?
3:10:02 PM PLAYER_COMMAND: Birchaw: /tm abroadcast Are you seeing something from this?
3:10:02 PM CONSOLE: ERROR]: null
3:10:02 PM CONSOLE: exception executing command 'tm' in plugin TitleManager v2.0.6
3:10:02 PM CONSOLE: Source) [?:1.8.0_121]
3:10:02 PM CONSOLE: Source) [?:1.8.0_121]
3:10:02 PM CONSOLE: Source) [?:1.8.0_121]
3:10:02 PM CONSOLE: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;`

**Comment by Puharesource** [comment]
What's the output of `/version` ?

**Comment by BobKyle** [comment]
`3:40:56 PM CONSOLE: [INFO] This server is running CraftBukkit version git-Bukkit-cb61ac0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
3:40:56 PM CONSOLE: [INFO] Checking version, please wait...
3:40:56 PM CONSOLE: [INFO] You are running the latest version`

Hmm, I may have installed Spigot incorrectly I think?

**Comment by Puharesource** [comment]
Yeah, you aren't running Spigot, you're running CraftBukkit

**Comment by BobKyle** [comment]
Yep, found my issue. MCMA had switched to CraftBukkit from Spigot without me noticing. 
Working now! Sorry for the trouble
