### ISSUE TITLE
Plugin not working on my Server

### ISSUE THREAD

**Issue by HelixCord** [Puharesource/TitleManager#115]
The plugin does not work on my server as of version 2.0. The console is spamming this error if I use a command:

```
[23:09:16] [Server thread/WARN]: Unexpected exception while parsing console command "tm reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'tm' in plugin TitleManager v2.0.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ExceptionInInitializerError
	at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:619) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:133) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IScoreboardCriteria$EnumScoreboardHealthDisplay
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.<init>(ReflectionClass.kt:32) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getInnerReflectionClass(ReflectionClass.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.Provider18.<init>(Providers.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.Provider18.<clinit>(Providers.kt:41) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:619) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:133) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 8 more
```

**Comment by Puharesource** [comment]
What version of Spigot are you using?
What's the output of `/version` ?

**Comment by Puharesource** [comment]
Caused by 1.7.10 Protocol Hack and 1.8 -> 1.8.2

**Comment by HelixCord** [comment]
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by HelixCord** [comment]
I have the plugin also run on another server with the same version. Everything works great there.
