### ISSUE TITLE
Console is spamming errors

### ISSUE THREAD

**Issue by HelixCord** [Puharesource/TitleManager#116]
Sorry I have a problem again. I have now brought the server to the 1.8.8 and still have the same problem. The error:
 ```
[18:47:55] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.0.0
rx.exceptions.OnErrorNotImplementedException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[?:?]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[?:?]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[?:?]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[?:?]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[?:?]
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[?:?]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[?:?]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[?:?]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) ~[?:?]
	at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getMethod(ReflectionClass.kt:12) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.ReflectionPlayerExtensionsKt.sendNMSPacket(ReflectionPlayerExtensions.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.scoreboard.ScoreboardManager.createScoreboardWithName(ScoreboardManager.kt:69) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.giveScoreboard(APIProvider.kt:645) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.giveScoreboard(TitleManagerPlugin.kt:703) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.giveScoreboard(PlayerExtensions.kt:150) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$28.call(TitleManagerPlugin.kt:517) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$28.call(TitleManagerPlugin.kt:44) ~[?:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[?:?]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[?:?]
	... 19 more
[18:47:55] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.0.0
rx.exceptions.OnErrorNotImplementedException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[?:?]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[?:?]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[?:?]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[?:?]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[?:?]
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[?:?]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[?:?]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[?:?]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
	at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) ~[?:?]
	at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getMethod(ReflectionClass.kt:12) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.ReflectionPlayerExtensionsKt.sendNMSPacket(ReflectionPlayerExtensions.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:634) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$4.invoke(TitleManagerPlugin.kt:415) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:502) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:44) ~[?:?]
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[?:?]
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[?:?]
	... 19 more`
and another error:
`[18:47:56] [RxComputationScheduler-1/WARN]: Exception in thread "RxComputationScheduler-1" 
[18:47:56] [RxComputationScheduler-1/WARN]: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:47:56] [RxComputationScheduler-1/WARN]: Caused by: rx.exceptions.OnErrorNotImplementedException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[18:47:56] [RxComputationScheduler-1/WARN]: 	... 7 more
[18:47:56] [RxComputationScheduler-1/WARN]: Caused by: java.lang.NoSuchMethodException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getMethod(ReflectionClass.kt:12)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.reflections.ReflectionPlayerExtensionsKt.sendNMSPacket(ReflectionPlayerExtensions.kt:29)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.sendActionbar(APIProvider.kt:581)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.sendActionbarWithPlaceholders(APIProvider.kt:586)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendActionbarWithPlaceholders(TitleManagerPlugin.kt:683)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendActionbar(PlayerExtensions.kt:54)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$3.invoke(TitleManagerPlugin.kt:402)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:488)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:44)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
[18:47:56] [RxComputationScheduler-1/WARN]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
[18:47:56] [RxComputationScheduler-1/WARN]: 	... 11 more
[18:47:56] [RxComputationScheduler-2/WARN]: Exception in thread "RxComputationScheduler-2" 
[18:47:56] [RxComputationScheduler-2/WARN]: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:47:56] [RxComputationScheduler-2/WARN]: Caused by: rx.exceptions.OnErrorNotImplementedException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[18:47:56] [RxComputationScheduler-2/WARN]: 	... 7 more
[18:47:56] [RxComputationScheduler-2/WARN]: Caused by: java.lang.NoSuchMethodException: Couldn't find constructor for net.minecraft.server.v1_8_R3.NetworkManager.
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getMethod(ReflectionClass.kt:12)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.reflections.ReflectionPlayerExtensionsKt.sendNMSPacket(ReflectionPlayerExtensions.kt:29)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.sendTimings(APIProvider.kt:544)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.sendTitle(APIProvider.kt:432)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.APIProvider.sendTitleWithPlaceholders(APIProvider.kt:464)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendTitleWithPlaceholders(TitleManagerPlugin.kt:655)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendTitle(PlayerExtensions.kt:10)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$1.invoke(TitleManagerPlugin.kt:368)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:449)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:44)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
[18:47:56] [RxComputationScheduler-2/WARN]: 	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
[18:47:56] [RxComputationScheduler-2/WARN]: 	... 11 more
```

All installed plugins:
```
WorldEdit, OnlyProxyJoin, Essentials, PlaceholderAPI, UnitySystem, SpawnJoin, NametagEdit, BungeePerms, Lockette, Votifier, ProtocolLib, WorldGuard, Multiverse-Core, NoCheatPlus, ScheduledCommands, EssentialsChat, SQLibrary, CommandSync, Multiverse-Portal, GAListener, Vault , EssentialsSpawn, PlayerParticles, TitleManager, CombatLog, ItemSlotMachine, RandomTP, KillerMoney, HolographicDisplays, PlayerPoints, InfoBoardReborn, Citizens, Shopkeepers, ChestCommands, CommandNPC, CratesPlus
```

**Comment by Puharesource** [comment]
Try to update TitleManager to the latest version (You're on 2.0.0, while 2.0.6 is out)

**Comment by HelixCord** [comment]
On the latest Version I get this error:
`[20:24:45] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tm' in plugin TitleManager v2.0.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.ExceptionInInitializerError
	at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:619) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:133) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IScoreboardCriteria$EnumScoreboardHealthDisplay
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_121]
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.<init>(ReflectionClass.kt:32) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getInnerReflectionClass(ReflectionClass.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.Provider18.<init>(Providers.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.Provider18.<clinit>(Providers.kt:41) ~[?:?]
	at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:619) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
	at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
	at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
	at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:133) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
	at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:156) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebac-7019900]
	... 14 more`

**Comment by Puharesource** [comment]
To fix this issue, you'll either have to compile the project yourself or join the support chat. (Seeing as this fix is currently only available in a development build)
