### ISSUE TITLE
Console spamming errors when player joins.

### ISSUE THREAD

**Issue by TheTomTom3901** [Puharesource/TitleManager#122]
Whenever a player joins the console is spammed with

[16:32:27 ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.0.6
java.lang.ExceptionInInitializerError
        at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
        at io.puharesource.mc.titlemanager.scoreboard.ScoreboardManager.createScoreboardWithName(ScoreboardManager.kt:59) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.giveScoreboard(APIProvider.kt:645) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.giveScoreboard(TitleManagerPlugin.kt:703) ~[?:?]
        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.giveScoreboard(PlayerExtensions.kt:150) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$28.call(TitleManagerPlugin.kt:517) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$28.call(TitleManagerPlugin.kt:44) ~[?:?]
        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[?:?]
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[?:?]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[?:?]
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
        at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) ~[?:?]
        at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.IScoreboardCriteria$EnumScoreboardHealthDisplay
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_121]
        at io.puharesource.mc.titlemanager.reflections.ReflectionClass.<init>(ReflectionClass.kt:32) ~[?:?]
        at io.puharesource.mc.titlemanager.reflections.ReflectionClass.getInnerReflectionClass(ReflectionClass.kt:29) ~[?:?]
        at io.puharesource.mc.titlemanager.reflections.Provider18.<init>(Providers.kt:57) ~[?:?]
        at io.puharesource.mc.titlemanager.reflections.Provider18.<clinit>(Providers.kt:41) ~[?:?]
        ... 28 more
[16:32:27 ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.0.6
java.lang.NoClassDefFoundError: Could not initialize class io.puharesource.mc.titlemanager.reflections.Provider18
        at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.setHeaderAndFooter(APIProvider.kt:619) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.setHeaderWithPlaceholders(APIProvider.kt:603) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.setHeaderWithPlaceholders(TitleManagerPlugin.kt:691) ~[?:?]
        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListHeader(PlayerExtensions.kt:108) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:372) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toHeaderAnimation$4.invoke(APIProvider.kt:43) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:82) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:57) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$4.invoke(TitleManagerPlugin.kt:415) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:502) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:44) ~[?:?]
        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[?:?]
        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[?:?]
        at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[?:?]
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
        at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) ~[?:?]
        at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:272) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:156) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:800) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[16:32:27 INFO]: TheTomTom3901[/192.168.0.1:51156] logged in with entity id 81 at ([world] -321.37941847690774, 13.0, 744.4762040390833)
[16:32:28 WARN]: Exception in thread "RxComputationScheduler-1"
[16:32:28 WARN]: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
[16:32:28 WARN]:        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
[16:32:28 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:32:28 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:32:28 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.puharesource.mc.titlemanager.reflections.Provider18
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.APIProvider.sendActionbar(APIProvider.kt:562)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.APIProvider.sendActionbarWithPlaceholders(APIProvider.kt:586)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendActionbarWithPlaceholders(TitleManagerPlugin.kt:683)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendActionbar(PlayerExtensions.kt:54)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$3.invoke(TitleManagerPlugin.kt:402)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:488)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$20.call(TitleManagerPlugin.kt:44)
[16:32:28 WARN]:        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
[16:32:28 WARN]:        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
[16:32:28 WARN]:        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
[16:32:28 WARN]:        at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
[16:32:28 WARN]:        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
[16:32:28 WARN]:        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[16:32:28 WARN]:        ... 7 more
[16:32:28 WARN]: Exception in thread "RxComputationScheduler-2"
[16:32:28 WARN]: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
[16:32:28 WARN]:        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
[16:32:28 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:32:28 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:32:28 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:32:28 WARN]: Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.puharesource.mc.titlemanager.reflections.Provider18
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.reflections.NMSManager.getClassProvider(NMSManager.kt:40)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.APIProvider.sendTitle(APIProvider.kt:429)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.APIProvider.sendTitleWithPlaceholders(APIProvider.kt:464)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendTitleWithPlaceholders(TitleManagerPlugin.kt:655)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendTitle(PlayerExtensions.kt:10)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$1.invoke(TitleManagerPlugin.kt:368)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:449)
[16:32:28 WARN]:        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:44)
[16:32:28 WARN]:        at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
[16:32:28 WARN]:        at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
[16:32:28 WARN]:        at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
[16:32:28 WARN]:        at rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
[16:32:28 WARN]:        at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
[16:32:28 WARN]:        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[16:32:28 WARN]:        ... 7 more

Any help would be appreciated :D

**Comment by supertassu** [comment]
What version are you on? I got excactly same message on 1.8, 1.8.9+ works.

**Comment by TheTomTom3901** [comment]
The issue is fixed in a beta version. if u join the discord chat there is a fix there

**Comment by Puharesource** [comment]
Like @TheTomTom3901 said
