### ISSUE TITLE
Error when 2 plugins are utilizing the same library.

### ISSUE THREAD

**Issue by KillerAntMC** [Puharesource/TitleManager#129]
Hello, I ran into a problem when testing with FactionsFly ([https://www.spigotmc.org/resources/16562/](url)). When I have both titlemanager and factionsfly running together, titlemanager fails to load. When I remove factionsfly, it enables. This is the error that comes up:

`[11:30:51] [Server thread/INFO]: [TitleManager] Enabling TitleManager v2.0.6
[11:30:51] [Server thread/ERROR]: Error occurred while enabling TitleManager v2.0.6 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "rx/Scheduler"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_121]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at io.puharesource.mc.titlemanager.InternalsKt.<clinit>(Internals.kt:20) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[11:30:51] [Server thread/INFO]: [TitleManager] Disabling TitleManager v2.0.6`

**Comment by Puharesource** [comment]
This was fixed in 1b851a6aff6a306052c603f972c91ad8ceb8679d next release will feature this, if you want the update now, feel free to join my Discord group for a pre-release.
