### ISSUE TITLE
Console issues

### ISSUE THREAD

**Issue by Akarus95** [Puharesource/TitleManager#147]
Hello, I got some issues with Titlemanager, it works well but I got some errors on the console when someone's connecting to the server.

```
CONSOLE: WARN: Exception in thread "RxComputationScheduler-1"
CONSOLE: WARN: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
CONSOLE: WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
CONSOLE: WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
CONSOLE: WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)
CONSOLE: WARN]: Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.OnErrorNotImplementedException: Parameter specified as non-null is null: method io.puharesource.mc.titlemanager.extensions.StringExtensionsKt.color, parameter $receiver
CONSOLE:WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
CONSOLE:WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
CONSOLE:WARN]: at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
CONSOLE:WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
CONSOLE: WARN]: ... 7 more
CONSOLE: WARN]: Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method io.puharesource.mc.titlemanager.extensions.StringExtensionsKt.color, parameter $receiver
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.extensions.StringExtensionsKt.color(StringExtensions.kt)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:459)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:47)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
CONSOLE: WARN]: at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
CONSOLE: WARN]: ... 11 more
```

And that's my config.yml : 

```
############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# Config comment style borrowed from the Essentials config.
#
# If you want to use special characters (ASCII, UTF-8 characters) in the config, you need to save the file as UTF-8.
#   - If you don't know how this is done, you can see the guide on the wiki: https://github.com/Puharesource/TitleManager/wiki/Unicode---UTF-8-characters-for-TitleManager
#
# Config errors, such as the plugin not loading or the config resetting can be fixed by ensuring that:
#   - No tabs are present: YAML only allows spaces.
#   - You have escaped all apostrophes or quotes in your text:
#      - If you surround your text with apostrophes like this 'don't', double all of your apostrophes like this: 'don''t'
#      - If you surround your text with quotes like this "Quote: "hello"", switch to apostrophes instead like this 'Quite: "hello"'.
#
# If you've got problems:
#   - Join the Discord server here: https://discord.gg/NwdtW2d
#   - Write a ticket on the Issue Tracker here: https://github.com/Puharesource/TitleManager/issues
#
# 1 second = 20 ticks
#
# For more information check: https://github.com/Puharesource/TitleManager/wiki

############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# Never change this value
config-version: 4

# Toggles debug mode, which prints additional information when the plugin does something.
debug: false

# Toggles whether or not all of the features of TitleManager will be toggled.
using-config: true

# Toggles whether or not all of the BungeeCord functionality will be toggled.
using-bungeecord: false

# (Feature only works on 1.7-1.8 Protocol Hack)
# Toggles whether or not 1.7 players will see actionbar messages when they're holding an item.
legacy-client-support: false

# Toggles whether or not the plugin should warn administrators if there's a new version out.
check-for-updates: true

############################################################
# +------------------------------------------------------+ #
# |                     Player List                      | #
# +------------------------------------------------------+ #
############################################################

# Sets the header and footer of the player list. (Shown when you hold the TAB key.)

player-list:

  # Toggles this feature.
  enabled: false

  # Sets the header of the player list.
  #
  # Single line format.
  # header: 'My header text'
  #
  # Multiple line format.
  # header:
  # - 'My first line'
  # - 'My second line'
  # - 'My third line'
  header:
  - ''
  - '${shine:[0;2;0][0;25;0][0;25;0][&3;&b]Okonaye}'
  - ''

  # Sets the footer of the player list.
  #
  # Single line format.
  # footer: 'My footer text'
  #
  # Multiple line format.
  # footer:
  # - 'My first line'
  # - 'My second line'
  # - 'My third line'
  footer:
  - '${right-to-left} &b%{online}&7/&b%{max} &7Online Players ${left-to-right}'

############################################################
# +------------------------------------------------------+ #
# |                    Welcome Title                     | #
# +------------------------------------------------------+ #
############################################################

# Sets the title that is sent to the player when they join the server.

welcome-title:

  # Toggles this feature.
  enabled: true

  # The title shown.
  title: 'Bienvenue sur le serveur'

  # The subtitle shown.
  #subtitle: 'Hope you enjoy your stay'

  # The time it takes for the title to fade into the screen. (In ticks)
  fade-in: 20

  # The time it takes for the title to stay on the screen. (In ticks)
  stay: 40

  # The time it takes for the title to fade out of the screen. (In ticks)
  fade-out: 20

  # The title shown when the player joins the server for the first time.
  first-join:

    # The title shown.
    title: 'Bienvenue sur le serveur'

    # The subtitle shown.
    #subtitle: 'This is your first time!'

############################################################
# +------------------------------------------------------+ #
# |                  Welcome Actionbar                   | #
# +------------------------------------------------------+ #
############################################################

# Sets the actionbar that is sent to the player when they join the server.

#welcome-actionbar:

  # Toggles this feature.
  #enabled: true

  # The message shown.
  #title: 'Welcome to My Server'

  # The message shown when the player joins the server for the first time.
  #first-join: 'Welcome to My Server, this is your first time!'

############################################################
# +------------------------------------------------------+ #
# |                     Placeholders                     | #
# +------------------------------------------------------+ #
############################################################

# Configures anything placeholder related.

placeholders:

  # The format used by the balance placeholder.
  number-format:

    # Toggles this feature.
    enabled: false

    # The format used.
    format: '#,###.##'

  # The format used by the server-time placeholder.
  # The format used can be found here: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
  date-format: 'EEE, dd MMM yyyy HH:mm:ss z'

############################################################
# +------------------------------------------------------+ #
# |                      Scoreboard                      | #
# +------------------------------------------------------+ #
############################################################

# Sets the scoreboard (sidebar) that is sent to the player

scoreboard:

  # Toggles this feature
  enabled: true

  # The title displayed at the very top of the scoreboard
  # The title must consist of 32 or less characters (this includes color codes)
  title: '${shine:[0;2;0][0;25;0][0;25;0][&3&l;&b&l]Okonaye}'

  # The lines of the scoreboard (Maximum of 15 lines allowed)
  # Each line can only have 40 characters (this includes color codes)
  # Each line must also be unique, a work around would be to put a color code at the end your line, to make it unique.
  lines:
  - '&b&m------------------'
  - '&b &3&lPlayer Name:'
  - '&b%{name}'
  - '&r'
  - '&b &3&lPing:'
  - '&b%{ping} MS'
  - '&r&r'
  - '&b &3&lMoney:'
  - '&b%{balance}'
  - '&r&r&r'
  - '&b &3&lJoueurs:'
  - '&b%{online}&7/&b%{max}'
  - '&b&m------------------&r'

############################################################
# +------------------------------------------------------+ #
# |                      Announcer                       | #
# +------------------------------------------------------+ #
############################################################

# Automatically send titles and/or actionbar messages to the players on the server.

announcer:

  # Toggles this feature.
  enabled: false

  # The announcements
  #
  # The format:
  #
  # announcement-name:
  #   interval: 60                        (Seconds, Default: 60)
  #   timings:
  #     fade-in: 20                       (Ticks, Default: 20)
  #     stay: 40                          (Ticks, Default: 40)
  #     fade-out: 20                      (Ticks, Default: 20)
  #   titles:
  #   - 'First title'                     (The title sent)
  #   - 'Second title\nSecond subtitle'   (The next title sent, this time using \n to split the title and subtitle from each other)
  #   actionbar:
  #   - 'First actionbar'                 (The actionbar message sent)
  #   - 'The next actionbar sent'         (The next actionbar message sent)
  announcements:
    my-announcement:
      interval: 60
      timings:
        fade-in: 20
        stay: 40
        fade-out: 20
      titles:
      - '&aThis is the 1st title announcement\n&aThis is the subtitle'
      - '&bThis is the 2nd title announcement\n&bThis is the subtitle'
      actionbar:
      - '&aThis is the 1st actionbar announcement'
      - '&bThis is the 2nd actionbar announcement'

############################################################
# +------------------------------------------------------+ #
# |                       Messages                       | #
# +------------------------------------------------------+ #
############################################################

# Configures all of the messages sent to the users.

messages:
  # The message shown when a player doesn't have permission to run a command.
  no-permission: '&cYou do not have permission to run that command!'

  # The messages from the command /tm version
  command-version:
    description: 'Gives you the current running version of TitleManager'
    version: '&aThe server is running %version'

  # The messages from the command /tm reload
  command-reload:
    description: 'Reloads TitleManager'
    reloaded: '&aTitleManager reloaded'

  # The messages from the command /tm animations
  command-animations:
    description: 'Displays all loaded animations'
    format: '&aLoaded animations (&f%count&a): %animations'
    separator: '&f, &a'

  # The messages from the command /tm scripts
  command-scripts:
    description: 'Displays all loaded scripts'
    format: '&aLoaded scripts (&f%count&a): %scripts'
    separator: '&f, &a'

  # The messages from the command /tm broadcast
  command-broadcast:
    description: 'Broadcasts a title to the server'
    usage: '<title>|<title\nsubtitle>'
    title-sent: '&aYou have broadcasted the title "&r%title&a".'
    subtitle-sent: '&aYou have broadcasted the subtitle "&r%subtitle&a".'
    both-sent: '&aYou have broadcasted the titles "&r%title&a" "&r%subtitle&a".'

  # The messages from the command /tm abroadcast
  command-abroadcast:
    description: 'Broadcasts an actionbar title to the server'
    usage: '<title>'
    sent: '&aYou have broadcasted the actionbar title "&r%title&a".'

  # The messages from the command /tm message
  command-message:
    description: 'Sends a title to the specified player'
    usage: '<player> <title>|<title\nsubtitle>'
    title-sent: '&aYou have sent %player the title "&r%title&a".'
    subtitle-sent: '&aYou have sent %player the subtitle "&r%subtitle&a".'
    both-sent: '&aYou have sent %player the titles "&r%title&a" "&r%subtitle&a".'
    invalid-player: '&c%player is not a valid player.'

  # The messages from the command /tm amessage
  command-amessage:
    description: 'Sends an actionbar title to the specified player'
    usage: '<player> <title>'
    sent: '&aYou have sent %player the actionbar title "&r%title&a".'
    invalid-player: '&c%player is not a valid player.'
```

**Comment by Puharesource** [comment]
You have commented out the actionbar field in your config by placing a `#` in front, if you want to disable the actionbar welcome message set `enabled` to `false` instead.
