### ISSUE TITLE
Issue with %{tps} placeholder

### ISSUE THREAD

**Issue by CDAGaming** [Puharesource/TitleManager#150]
```
[02:46:12 ERROR]: Command Dispatched Async: tps
[02:46:12 ERROR]: Please notify author of plugin causing this execution to fix this bug! see: http://bit.ly/1oSiM6C
java.lang.Throwable: null
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:654) [patched_1.12.1.jar:git-Paper-1190]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:590) [patched_1.12.1.jar:git-Paper-1190]
        at io.puharesource.mc.titlemanager.placeholder.PlaceholderTps.getOutput(PlaceholderTps.kt:11) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.placeholder.PlaceholderTps.getTps(PlaceholderTps.kt:17) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerPlaceholders$12.invoke(TitleManagerPlugin.kt:548) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerPlaceholders$12.invoke(TitleManagerPlugin.kt:48) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:155) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.APIProvider.setFooterWithPlaceholders(APIProvider.kt:582) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.setFooterWithPlaceholders(TitleManagerPlugin.kt:762) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setPlayerListFooter(PlayerExtensions.kt:126) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.APIProvider$toFooterAnimation$4.invoke(APIProvider.kt:346) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.APIProvider$toFooterAnimation$4.invoke(APIProvider.kt:42) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:83) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:90) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:11) [TitleManager-2.0.9.jar:?]
        at io.puharesource.mc.titlemanager.scheduling.AsyncScheduler$scheduleRaw$1.run(AsyncScheduler.kt:43) [TitleManager-2.0.9.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by CDAGaming** [comment]
@Puharesource 
OS: Ubuntu 16.10
Server: PaperSpigot 1.12.1

**Comment by CDAGaming** [comment]
@Puharesource 
Update: Issue is also Evident on Windows, Unable to test on MacOS

**Comment by CDAGaming** [comment]
Any Status on this?

**Comment by Puharesource** [comment]
I'm in the middle of moving, I'll fix this once I'm settled. Sorry for the inconvenience for now, you can try out PlaceholderAPI's placeholders, I'm pretty sure it has got a `%tps%` placeholder.

**Comment by CDAGaming** [comment]
Well at this time, I've been using ConsoleSpamFix so this doesn't show in my logs

Thanks again and happy moving
