### ISSUE TITLE
when player login the server the plugin error

### ISSUE THREAD

**Issue by Juliandilanda** [Puharesource/TitleManager#154]
```
[20:52:04 WARN]: Exception in thread "RxComputationScheduler-1"
[20:52:04 WARN]: java.lang.IllegalStateException: Fatal Exception thrown on Sche
duler.Worker thread.
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.sc
hedulers.ScheduledAction.run(ScheduledAction.java:59)
[20:52:04 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[20:52:04 WARN]: at java.util.concurrent.FutureTask.run(Unknown Source)
[20:52:04 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.access$201(Unknown Source)
[20:52:04 WARN]: at java.util.concurrent.ScheduledThreadPoolExecutor$Sche
duledFutureTask.run(Unknown Source)
[20:52:04 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(Unk
nown Source)
[20:52:04 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(Un
known Source)
[20:52:04 WARN]: at java.lang.Thread.run(Unknown Source)
[20:52:04 WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Playe
r.spigot()Lorg/bukkit/entity/Player$Spigot;
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.APIProvider.sendActio
nbar(APIProvider.kt:533)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.APIProvider.sendActio
nbarWithPlaceholders(APIProvider.kt:554)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin.se
ndActionbarWithPlaceholders(TitleManagerPlugin.kt:748)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.extensions.PlayerExte
nsionsKt.sendActionbar(PlayerExtensions.kt:54)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin.se
ndActionbarFromText(TitleManagerPlugin.kt:632)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin.ac
cess$sendActionbarFromText(TitleManagerPlugin.kt:48)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$re
gisterListeners$15.call(TitleManagerPlugin.kt:470)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.TitleManagerPlugin$re
gisterListeners$15.call(TitleManagerPlugin.kt:48)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.ut
il.ActionSubscriber.onNext(ActionSubscriber.java:39)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.observers.S
afeSubscriber.onNext(SafeSubscriber.java:134)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.op
erators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.op
erators.OperatorDelay$1$3.call(OperatorDelay.java:87)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.sc
hedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189
)
[20:52:04 WARN]: at io.puharesource.mc.titlemanager.shaded.rx.internal.sc
hedulers.ScheduledAction.run(ScheduledAction.java:55)
[20:52:04 WARN]: ... 7 more
```

**Comment by Puharesource** [comment]
I need more information than that, what version are you on?

**Comment by Juliandilanda** [comment]
i am using the 1.11.2 spigot server version

**Comment by Puharesource** [comment]
What version of the plugin?

**Comment by Juliandilanda** [comment]
is the 2.0.9

**Comment by Puharesource** [comment]
You're not on Spigot, you're on CraftBukkit, please use spigot.jar instead of craftbukkit.jar

**Comment by Juliandilanda** [comment]
okok , but why it sent me warning
just cause the craftbukkit?

**Comment by Puharesource** [comment]
Yeah, I'm using Spigot specific features, which is why you're required to use Spigot

**Comment by Juliandilanda** [comment]
um i confuse , i forgot can craftbukkit use the plugins? or same of spigot and carftbukkit can be use the plugin too? if not i got to change to spigot

**Comment by Puharesource** [comment]
Not all Spigot plugins can run on CraftBukkit, but all CraftBukkit plugins run on Spigot

**Comment by Juliandilanda** [comment]
oh thanks
