### ISSUE TITLE
Issue: Exception in initializer

### ISSUE THREAD

**Issue by GoliathLabs** [Puharesource/TitleManager#157]
```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```
Java: 
```
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```
Paper/Spigot:
```
> version
[23:09:13 INFO]: This server is running Paper version git-Paper-1248 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[23:09:13 INFO]: You are running the latest version
> 
```
```
Stacktrace:
```[22:38:55 INFO]: [TitleManager] Enabling TitleManager v2.0.9
[22:38:56 ERROR]: Error occurred while enabling TitleManager v2.0.9 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.loadAnimations(TitleManagerPlugin.kt:843) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:67) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Paper-1248]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [JavaPluginLoader.class:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [SimplePluginManager.class:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [CraftServer.class:git-Paper-1248]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [CraftServer.class:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [MinecraftServer.class:?]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [MinecraftServer.class:?]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [MinecraftServer.class:?]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [DedicatedServer.class:?]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: ScriptEngineManager().getEngineByName("nashorn") must not be null
	at io.puharesource.mc.titlemanager.script.ScriptManager.<init>(ScriptManager.kt:18) ~[?:?]
	at io.puharesource.mc.titlemanager.script.ScriptManager.<clinit>(ScriptManager.kt:17) ~[?:?]
	... 13 more
[22:38:56 INFO]: [TitleManager] Disabling TitleManager v2.0.9
```

**Comment by mikroskeem** [comment]
I must note that given exception only happens on OpenJDK. Plugin launches fine with Oracle's JDK.

Alternative way (besides using Oracle JRE/JDK) for solving this is getting `nashorn.jar` from somewhere and and adding to jvm boot classpath (using `-Xbootclasspath/a:$(pwd)/libs/nashorn.jar` for example).  
Given solution is not 100% fix, as boot classpath argument cannot be added to shared server hostings [without dirty hacks like this](https://gist.github.com/mikroskeem/c04fba00f99f99fee1e12fbb76c04889). I know few server hosts where given issue pops up as well (one example is server.pro)

**Comment by Puharesource** [comment]
I'm not really planning on bundling in nor downloading Nashorn at runtime, I'll explore some solutions, but I think I might just have to disable the scripts when it's run through OpenJDK.
