### ISSUE TITLE
KoTH Placeholders issue

### ISSUE THREAD

**Issue by Rogz256** [Puharesource/TitleManager#159]
Hey guys,
I saw the new uptade of KoTH (King of the Hill) placeholders using placeholdersAPI expansion and it seems be issue. It doesn't work with that placeholders.

KoTH extension to PlaceHolderAPI
https://www.spigotmc.org/resources/expansion-koth.27094/

```
Error Log:
org.bukkit.command.CommandException: Unhandled exception executing command 'tm' in plugin TitleManager v2.0.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot194.jar:git-Spigot-c6871e2-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: subside/plugins/koth/adapter/KothHandler
        at me.F64.papiexpansions.koth.ExpansionKoTH.onPlaceholderRequest(ExpansionKoTH.java:41) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:132) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.setScoreboardValueWithPlaceholders(APIProvider.kt:650) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.setScoreboardValueWithPlaceholders(TitleManagerPlugin.kt:782) ~[?:?]
        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setScoreboardValue(PlayerExtensions.kt:168) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:358) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:42) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:83) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:58) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:152) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:157) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot194.jar:git-Spigot-c6871e2-0cd0397]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: subside.plugins.koth.adapter.KothHandler
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at me.F64.papiexpansions.koth.ExpansionKoTH.onPlaceholderRequest(ExpansionKoTH.java:41) ~[?:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:342) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:132) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider.setScoreboardValueWithPlaceholders(APIProvider.kt:650) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.setScoreboardValueWithPlaceholders(TitleManagerPlugin.kt:782) ~[?:?]
        at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.setScoreboardValue(PlayerExtensions.kt:168) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:358) ~[?:?]
        at io.puharesource.mc.titlemanager.APIProvider$toScoreboardValueAnimation$4.invoke(APIProvider.kt:42) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:83) ~[?:?]
        at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:58) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.reloadPlugin(TitleManagerPlugin.kt:152) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:8) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1$1.invoke(CommandReload.kt:6) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandExecutorKt.commandExecutor(CommandExecutor.kt:188) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:7) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.CommandReload$1.invoke(CommandReload.kt:6) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.TMSubCommand.runCommand(TMSubCommand.kt:20) ~[?:?]
        at io.puharesource.mc.titlemanager.commands.TMCommand.onCommand(TMCommand.kt:157) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot194.jar:git-Spigot-c6871e2-0cd0397]
        ... 15 more
```

Thanks, hope it get fixed!

**Comment by Puharesource** [comment]
This is an issue with PlaceholderAPI
