### ISSUE TITLE
Titlemanager is not working

### ISSUE THREAD

**Issue by DarkPotato23** [Puharesource/TitleManager#171]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31) ~[?:?]
04.05 14:20:49 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [my.jar:git-Spigot-4bd94dc-1c40a81]
04.05 14:20:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
04.05 14:20:49 [Server] INFO Caused by: java.lang.IllegalStateException: be.maximvdw.placeholdera…laceholders(player, text) must not be null
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:126) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:42) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:136) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.script.ScriptManager$getJavaScriptAnimation$1$1.next(ScriptManager.kt:75) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.script.ScriptManager$getJavaScriptAnimation$1$1.next(ScriptManager.kt:68) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.animations.AnimationSendablePart.updateText(PartBasedSendableAnimation.kt:132) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.getCurrentFrameText(PartBasedSendableAnimation.kt:44) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:58) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:501) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$24.call(TitleManagerPlugin.kt:48) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39) ~[?:?]
04.05 14:20:49 [Server] INFO at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134) ~[?:?]
04.05 14:20:49 [Server] INFO ... 20 more
04.05 14:20:49 [Connect] User Dark_Potato23, IP 162.250.153.15
04.05 14:20:49 [Multicraft] Dark_Potato23 ran command Message of the Day
04.05 14:20:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:20:49 [Server] WARN Put on of Maximvdw's premium placeholder plugins in the server!
04.05 14:20:50 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:20:50 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:20:50 [Server] WARN Put on of Maximvdw's premium placeholder plugins in the server!
04.05 14:20:50 [Server] WARN Put on of Maximvdw's premium placeholder plugins in the server!
04.05 14:20:50 [Server] WARN Exception in thread "RxComputationScheduler-1" 
04.05 14:20:50 [Server] WARN Exception in thread "RxComputationScheduler-2" 
04.05 14:20:50 [Server] WARN java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
04.05 14:20:50 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04.05 14:20:50 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04.05 14:20:50 [Server] WARN at java.lang.Thread.run(Thread.java:745)
04.05 14:20:50 [Server] WARN Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.OnErrorNotImplementedException: be.maximvdw.placeholdera…laceholders(player, text) must not be null
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04.05 14:20:50 [Server] WARN ... 7 more
04.05 14:20:50 [Server] WARN Caused by: java.lang.IllegalStateException: be.maximvdw.placeholdera…laceholders(player, text) must not be null
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:126)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:42)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:136)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider.sendActionbarWithPlaceholders(APIProvider.kt:554)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendActionbarWithPlaceholders(TitleManagerPlugin.kt:748)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendActionbar(PlayerExtensions.kt:54)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendActionbarFromText(TitleManagerPlugin.kt:632)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.access$sendActionbarFromText(TitleManagerPlugin.kt:48)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:470)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$15.call(TitleManagerPlugin.kt:48)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
04.05 14:20:50 [Server] WARN ... 11 more
04.05 14:20:50 [Server] WARN java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
04.05 14:20:50 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
04.05 14:20:50 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
04.05 14:20:50 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
04.05 14:20:50 [Server] WARN at java.lang.Thread.run(Thread.java:745)
04.05 14:20:50 [Server] WARN Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.OnErrorNotImplementedException: be.maximvdw.placeholdera…laceholders(player, text) must not be null
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.exceptions.Exceptions.throwOrReport(Exceptions.java:216)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onNext(OnSubscribeFilter.java:76)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorDelay$1$3.call(OperatorDelay.java:87)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:189)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
04.05 14:20:50 [Server] WARN ... 7 more
04.05 14:20:50 [Server] WARN Caused by: java.lang.IllegalStateException: be.maximvdw.placeholdera…laceholders(player, text) must not be null
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:126)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider$replaceText$mvdwReplace$1.invoke(APIProvider.kt:42)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider.replaceText(APIProvider.kt:136)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.APIProvider.sendTitleWithPlaceholders(APIProvider.kt:432)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendTitleWithPlaceholders(TitleManagerPlugin.kt:720)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.extensions.PlayerExtensionsKt.sendTitle(PlayerExtensions.kt:10)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.sendTitleFromText(TitleManagerPlugin.kt:598)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin.access$sendTitleFromText(TitleManagerPlugin.kt:48)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$10.call(TitleManagerPlugin.kt:431)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.TitleManagerPlugin$registerListeners$10.call(TitleManagerPlugin.kt:48)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
04.05 14:20:50 [Server] WARN at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
04.05 14:20:50 [Server] WARN ... 11 more

**Comment by DarkPotato23** [comment]
Now its spamming my console

**Comment by DarkPotato23** [comment]
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:48 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:48 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!
04.05 14:34:49 [Server] WARN There is no MVdW placeholder plugin installed!
04.05 14:34:49 [Server] WARN Put one of Maximvdw's premium placeholder plugins in the server!

**Comment by DarkPotato23** [comment]
when clearly is is installed
