### ISSUE TITLE
Every kicks, server hung up and tps down

### ISSUE THREAD

**Issue by thelex337** [Puharesource/TitleManager#182]
https://hastebin.com/raxavaleqi.md

**Comment by Puharesource** [comment]
Are you sure this is caused by TitleManager?

**Comment by thelex337** [comment]
`[15:12:31] [RxComputationScheduler-1/WARN]: Exception in thread "RxComputationScheduler-1" 
[15:12:31] [RxComputationScheduler-1/WARN]: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:12:31] [RxComputationScheduler-1/WARN]: Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.OnErrorNotImplementedException
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onError(OnSubscribeFilter.java:90)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorDelay$1$2.call(OperatorDelay.java:73)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[15:12:31] [RxComputationScheduler-1/WARN]: 	... 7 more
[15:12:31] [RxComputationScheduler-1/WARN]: Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.MissingBackpressureException
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:160)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:12:31] [RxComputationScheduler-1/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:12:31] [RxComputationScheduler-1/WARN]: 	... 1 more
[15:12:31] [RxComputationScheduler-2/WARN]: Exception in thread "RxComputationScheduler-2" 
[15:12:31] [RxComputationScheduler-2/WARN]: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:57)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:12:31] [RxComputationScheduler-2/WARN]: Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.OnErrorNotImplementedException
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OnSubscribeFilter$FilterSubscriber.onError(OnSubscribeFilter.java:90)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorDelay$1$2.call(OperatorDelay.java:73)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$1.call(EventLoopsScheduler.java:172)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
[15:12:31] [RxComputationScheduler-2/WARN]: 	... 7 more
[15:12:31] [RxComputationScheduler-2/WARN]: Caused by: io.puharesource.mc.titlemanager.shaded.rx.exceptions.MissingBackpressureException
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.shaded.rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:160)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at io.puharesource.mc.titlemanager.event.BukkitEventObservingKt$observeEventRaw$1$executor$1.execute(BukkitEventObserving.kt:31)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:298)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:157)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:814)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[15:12:31] [RxComputationScheduler-2/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[15:12:31] [RxComputationScheduler-2/WARN]: 	... 1 more`

**Comment by thelex337** [comment]
may be https://hastebin.com/edoyoriges.md

**Comment by Puharesource** [comment]
That's a strange issue, however, I don't think this is caused by TitleManager as that issue should only happen when loading the plugin. Not quite sure how you got that issue though.
