### ISSUE TITLE
Enabling Error

### ISSUE THREAD

**Issue by RRR9996** [Puharesource/TitleManager#183]
So, I was adding Placeholder so I could add more things like uptime. But when I restarted my server on server.pro it says enabling, and then almost instantly an error. This is it:
`[ERROR] Error occurred while enabling PlaceholderAPI v2.9.1 (Is it up to date?) java.lang.NoClassDefFoundError: com/google/gson/Gson at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.<init>(ExpansionCloudManager.java:54) ~[?:?] at me.clip.placeholderapi.PlaceholderAPIPlugin.enableCloud(PlaceholderAPIPlugin.java:182) ~[?:?] at me.clip.placeholderapi.PlaceholderAPIPlugin.onEnable(PlaceholderAPIPlugin.java:90) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.jar:git-Bukkit-7019900] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [craftbukkit-1.8.jar:git-Bukkit-7019900] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.jar:git-Bukkit-7019900] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:341) [craftbukkit-1.8.jar:git-Bukkit-7019900] at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [craftbukkit-1.8.jar:git-Bukkit-7019900] at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:394) [craftbukkit-1.8.jar:git-Bukkit-7019900] at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:362) [craftbukkit-1.8.jar:git-Bukkit-7019900] at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:317) [craftbukkit-1.8.jar:git-Bukkit-7019900] at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:190) [craftbukkit-1.8.jar:git-Bukkit-7019900] at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit-1.8.jar:git-Bukkit-7019900] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172] Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_172] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.8.jar:git-Bukkit-7019900] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.8.jar:git-Bukkit-7019900] at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_172] at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_172] ... 14 more`

I hope someone can help.

Oh, and also, i'm not sure if this was from 1.13, but fences, doors, and glass broke. When I right-click on a villager, it says: entity.Villager.<classes>

**Comment by RRR9996** [comment]
Wrong thing sorry!!
