### ISSUE TITLE
1.7:Report an error when the plugin starts

### ISSUE THREAD

**Issue by yuyuko233** [Puharesource/TitleManager#252]
Report an error when the plugin starts
```[12:21:58 INFO]: [TitleManager] Enabling TitleManager v2.1.6
[12:22:01 ERROR]: Error occurred while enabling TitleManager v2.1.6 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at io.puharesource.mc.titlemanager.internal.reflections.NMSManager.getClassProvider(NMSManager.kt:45) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.NMSUtil.setHeaderAndFooter(NMSUtil.kt:70) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.APIProvider.setHeaderAndFooter(APIProvider.kt:538) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.APIProvider.setFooter(APIProvider.kt:515) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.APIProvider.setFooterWithPlaceholders(APIProvider.kt:518) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.setFooterWithPlaceholders(TitleManagerPlugin.kt) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.extensions.PlayerExtensionsKt.setPlayerListFooter(PlayerExtensions.kt:127) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.APIProvider$toFooterAnimation$4.invoke(APIProvider.kt:327) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.APIProvider$toFooterAnimation$4.invoke(APIProvider.kt:40) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.animations.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:80) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.animations.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:55) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.startPlayerTasks(TitleManagerPlugin.kt:166) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:93) ~[?:?]
```

**Comment by Puharesource** [comment]
The only version of 1.7 the plugin supports is the 1.7/1.8 Protocol Hack version
