### ISSUE TITLE
NPE Thrown upon enabling of plugin (Plugin still runs however)

### ISSUE THREAD

**Issue by CharlieSay** [Puharesource/TitleManager#273]
**Describe the bug**
Upon start-up of the server, the plugin throws out a few warnings and then an NPE. 
`io.puharesource.mc.titlemanager.shaded.kotlin.KotlinNullPointerException: null`
However, after the bug the plugin still works, so it must be resolved later on. 

So not an urgent bug, but one that probably shouldn't be happening in the first place.

**To Reproduce**
1. Use plugin on Spigot, 1.15.2
2. See an error in the startup.

**Expected behavior**
Upon the start-up of the plugin inside the server, the plugin should start without any stack trace errors.

**Screenshots**
N/A

**Stacktrace / Error**
Please check the console for any errors that TitleManager might be producing.
`[08:30:48] [Server thread/INFO]: [TitleManager] Enabling TitleManager v2.2.7
[08:30:48] [Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[08:30:49] [Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
io.puharesource.mc.titlemanager.shaded.kotlin.KotlinNullPointerException: null
[08:30:49] [Server thread/ERROR]: Error occurred while enabling TitleManager v2.2.7 (Is it up to date?)
at io.puharesource.mc.titlemanager.internal.config.TMConfigMain$announcer$2.invoke(TMConfig.kt:48) ~[?:?]
at io.puharesource.mc.titlemanager.internal.config.TMConfigAnnouncer.<init>(TMConfig.kt:107) ~[?:?]
at io.puharesource.mc.titlemanager.shaded.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
at io.puharesource.mc.titlemanager.internal.config.TMConfigMain$announcer$2.invoke(TMConfig.kt:34) ~[?:?]
at io.puharesource.mc.titlemanager.internal.services.TitleManagerServiceSpigot.start(TitleManagerServiceSpigot.kt:54) ~[?:?]
at io.puharesource.mc.titlemanager.internal.config.TMConfigMain.getAnnouncer(TMConfig.kt) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:37) ~[?:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231] at io.puharesource.mc.titlemanager.internal.config.TMConfigMain.getAnnouncer(TMConfig.kt) ~[?:?]
at io.puharesource.mc.titlemanager.internal.services.TitleManagerServiceSpigot.start(TitleManagerServiceSpigot.kt:54) ~[?:?]
at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:37) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [Spigot-1.15.2.jar:git-Spigot-2040c4c-1872231]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Server information:**
 - TitleManager version: [2.2.7]
 - Spigot version: [Spigot 1.15.2]

**Additional context**
N/A

**Comment by Puharesource** [comment]
Should be fixed in version 2.3.0
