### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by BoyJamal** [Puharesource/TitleManager#274]
**Describe the bug**
Error when loading up, not exactly sure why

**To Reproduce**
loading in latest TitleManager on PaperSpigot 1.8.8

**Expected behavior**
Plugin to load successfully

**Screenshots**

**Stacktrace / Error**
[TitleManager] Enabling TitleManager v2.2.7
> [17:16:08 ERROR]: Error occurred while enabling TitleManager v2.2.7 (Is it up to date?)
io.puharesource.mc.titlemanager.shaded.kotlin.NotImplementedError: An operation is not implemented.
at io.puharesource.mc.titlemanager.internal.services.animation.ScriptServiceNotFound.loadBuiltinScripts(ScriptServiceNotFound.kt:10) ~[?:?]
at io.puharesource.mc.titlemanager.internal.services.TitleManagerServiceSpigot.start(TitleManagerServiceSpigot.kt:36) ~[?:?]
at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:37) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]

**Server information:**
 - TitleManager version: 2.27
 - Spigot version: PaperSpigot 1.8.8

**Additional context**

**Comment by Puharesource** [comment]
This will be fixed in version 2.3.0
