### ISSUE TITLE
Problem with SkyWars

### ISSUE THREAD

**Issue by aha0000** [Puharesource/TitleManager#280]
I setup TitleManager ver 2.2.7 on my server (spigot and after that players cannot start the game with any arena of SkyWars (plugin SkyWarsX). When all necessary players enter in arena the timer does not start the countdown. On server console admins can see repeated errors:

[23:08:33] [Server thread/WARN]: [Skywars] Task #3150 for Skywars v4.2 generated an exception
java.lang.NoClassDefFoundError: io/puharesource/mc/titlemanager/api/TitleObject
	at me.wazup.skywars.Arena$2.run(Arena.java:611) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[23:08:34] [Server thread/WARN]: [Skywars] Task #3150 for Skywars v4.2 generated an exception
java.lang.NoClassDefFoundError: io/puharesource/mc/titlemanager/api/TitleObject
	at me.wazup.skywars.Arena$2.run(Arena.java:611) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [server.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [server.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

and so on. But if I remove TitleManager plugin everything works fine.

Minecraft server 1.14.4
CraftBukkit version git-Spigot-9de398a-9c887d4 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by Puharesource** [comment]
The creator of SkyWars needs to update their plugin, they were accessing something that has been deprecated for years.

**Comment by aha0000** [comment]
thank you
