### ISSUE TITLE
Team tm-sb-0 already exists in this scoreboard

### ISSUE THREAD

**Issue by XXY233** [Puharesource/TitleManager#286]
**Describe the bug**
Unable to enter the server from BungeeCord

**Stacktrace / Error**
https://pastebin.com/YyJh42x8

**Server information:**
 - TitleManager version: 2.3.1
 - Spigot version: PaperSpigot 1.16.1

**Comment by Redstylt** [comment]
Same error here.
Paper MC 379 - MC 1.15.2
TitleManager 2.3.1.

CRITICAL ERROR !

**Comment by Maaattqc** [comment]
Same error when we have more than 1 player on the server.
Spigot 1.16.1
TitleManager 2.3.1

Information: No error with TitleManager 2.3.0

**Comment by darkstrayer** [comment]
Occurs when scoreboard is being used, i'm not impacted on servers when just using titles.

**Comment by flleeppyy** [comment]
Can also confirm I'm having this issue.
Spigot 1.16.1
TitleManager 2.3.1

**Comment by DaveTheCamper** [comment]
yep, same here.
Paper 1.16.1
TitleManager 2.3.1

**Comment by alan67160** [comment]
same error
BungeeCord Version Waterfall-366
Server Version SSSpigot-1.16.1-20200726-c4a1c4a
Plugin Version TitleManager-2.3.1

**Comment by xcraftman52** [comment]
Same Here!

**Comment by Rothes** [comment]
Same here!
`java.lang.IllegalArgumentException: Team tm-sb-0 already exists in this scoreboard
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
    at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:216)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:124)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Unknown Source`
when I use sRGB color in scoreboard, It should happen.
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:aa22fe6:1530 by md_5
This server is running CraftBukkit version git-Spigot-379750e-2e178b0 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
titlemanager 2.3.1

**Comment by Rothes** [comment]
NOTICE: Use PaperSpigot to avoid this bug.Everything is good.
This server is running Paper version git-Paper-141 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by flleeppyy** [comment]
Wait did a paper update fix this? Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Rothes <notifications@github.com> Date: 8/25/20  11:00 AM  (GMT-08:00) To: Puharesource/TitleManager <TitleManager@noreply.github.com> Cc: Flleeppyy <rainbowdjdash1@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Puharesource/TitleManager] Team tm-sb-0 already exists in this scoreboard (#286) 
NOTICE: Use PaperSpigot to avoid this bug.Everything is good.
This server is running Paper version git-Paper-141 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by Rothes** [comment]
> Wait did a paper update fix this? Sent from my T-Mobile 4G LTE Device -------- Original message --------From: Rothes <notifications@github.com> Date: 8/25/20 11:00 AM (GMT-08:00) To: Puharesource/TitleManager <TitleManager@noreply.github.com> Cc: Flleeppyy <rainbowdjdash1@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [Puharesource/TitleManager] Team tm-sb-0 already exists in this scoreboard (#286) NOTICE: Use PaperSpigot to avoid this bug.Everything is good. This server is running Paper version git-Paper-141 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT) —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

yes.You can have a try.

**Comment by HauserGrim** [comment]
For some players with enabled scoreboard, client lags or freeze
Paper 1.16.2 b174
Lagging stops if you turn it off, but some can't do it due to lags.

**Comment by parkerbryan** [comment]
Paper build 141 (1.16.2) did not resolve this for me as suggested by @Rothes , and neither did the following Paper builds:
138(1.16.1), 184, 185.

BungeeCord versions tested:
Build 1530 (used with Paper 138)
Build 1532 (used with Paper 141,184,185

In all cases, TitleManager 2.3.0 works, 2.3.1 does not.

Looks like this may be similar to or a duplicate of #288 except this is an immediate disconnection as soon as the connection is attempted, and their error is about "Objective vis7pj6051mm8kt7" already existing rather than "Team tm-sb-0" from the stackdump.

Setting debug to true did not result in any additional information from the plugin.

**Comment by mrzt721010** [comment]
fix it

**Comment by Envqu** [comment]
same

**Comment by xSorch** [comment]
Same

**Comment by areebuddinme** [comment]
This issue is still present, needs fixing

**Comment by DmitryRendov** [comment]
Same

**Comment by hkkongou** [comment]
similar problem happened to me 
purpur 1.16.5 #1055

TitleManager 2.3.3 ( this problem also exist in 2.3.0)
![image](https://user-images.githubusercontent.com/61608872/113533686-1b2d0100-9601-11eb-8b19-bc25c4187717.png)

**Comment by Puharesource** [comment]
> similar problem happened to me
> purpur 1.16.5 #1055
> 
> TitleManager 2.3.3 ( this problem also exist in 2.3.0)
> ![image](https://user-images.githubusercontent.com/61608872/113533686-1b2d0100-9601-11eb-8b19-bc25c4187717.png)

From reading the error it says `Team LD_it7 already exists in this scoreboard`, but TitleManager doesn't generate teams with that name. Are you sure this is caused by TitleManager?

**Comment by Mrd278** [comment]
![image](https://user-images.githubusercontent.com/47922198/121232686-7902f100-c8af-11eb-8813-7589530aff5c.png)
Please fix

**Comment by Baazigar007** [comment]
I am still getting this error. Does no one knows the fix?

**Comment by legendcuzican13** [comment]
I'm also getting a very similar error but slightly different. I'm also **not** using the "TitleManager" plugin.

Pic:

![Screenshot 2023-03-07 3 01 04 PM](https://user-images.githubusercontent.com/108838775/223551628-418719f8-44c1-4c28-abe9-b7ef1ce67959.png)
