### ISSUE TITLE
Scoreboard objective already exists - Disconnects players

### ISSUE THREAD

**Issue by TheCrunchy** [Puharesource/TitleManager#288]
Players get disconnected completely at random while using Waterfall and Paper. No errors in the paper console but this error in Waterfall.

https://pastebin.com/8n00BjMN

Hard to reproduce, happens at random. 

Running waterfall-365

and

![image](https://user-images.githubusercontent.com/13859025/88985962-8f244600-d2c9-11ea-84a2-d715c08f0d7d.png)

**Comment by Ansandr** [comment]
A familiar error, I temporarily solved it by rolling back to the old version of the plugin

**Comment by Permanently** [comment]
I've had this issue. A similar error, but not quite the same:
```
[/xxx.xxx.xxx.xxx:xxxx|Permanently] <-> DownstreamBridge <-> [lobby] - encountered exception
java.lang.IllegalArgumentException: Team tm-sb-0 already exists in this scoreboard
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:233) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.protocol.packet.Team.handle(Team.java:174) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[travertine.jar:git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[16:30:11 INFO]: [Permanently] disconnected with: The server you were previously on went down, you have been connected to a fallback server
```

Also on Travertine, and Paper:
`This server is running Travertine version git:Travertine-Bootstrap:1.16-R0.4-SNAPSHOT:10048da:154 by md_5`
`This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

**Comment by Patbox** [comment]
The same problem here it doen't disconnect, but it lags client:
![image](https://user-images.githubusercontent.com/39821509/91717784-7641d580-eb92-11ea-966e-22c445fa9d5d.png)
Tuinity 1.16.2, TM 2.3.1.

@Puharesource should check this one, as it's little server-breaking

**Comment by Patbox** [comment]
Still not fixed

**Comment by DeJayDev** [comment]
Can Reproduce, not addressed in this version. I will address this bug in a PR.

**Comment by AabegR** [comment]
Any updates on when it will be fixed?

**Comment by Permanently** [comment]
Still isn't fixed.

**Comment by Permanently** [comment]
???
