### ISSUE TITLE
[Critical] Plugin causes critical errors in iConomy (+ Vault)

### ISSUE THREAD

**Issue by Matmorcat** [Puharesource/TitleManager#31]
While the plugin is loaded, this error is spammed in console... Sometimes, people's balances also reset momentarily then return to normal a few seconds after.

[15:54:23 INFO]: [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

and...

[15:49:37] [Thread-27/WARN]: 	at sun.reflect.GeneratedConstructorAccessor482.newInstance(Unknown Source)
[15:49:37] [Thread-27/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:49:37] [Thread-27/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:343)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2334)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[15:49:37] [Thread-27/WARN]: 	at sun.reflect.GeneratedConstructorAccessor249.newInstance(Unknown Source)
[15:49:37] [Thread-27/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[15:49:37] [Thread-27/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[15:49:37] [Thread-27/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:571)
[15:49:37] [Thread-27/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:215)
[15:49:37] [Thread-27/WARN]: 	at net.coreprotect.database.Database.getConnection(Database.java:39)
[15:49:37] [Thread-27/WARN]: 	at net.coreprotect.consumer.Process.processConsumer(Process.java:26)
[15:49:37] [Thread-27/WARN]: 	at net.coreprotect.consumer.Consumer.run(Consumer.java:49)
[15:49:37] [Thread-27/WARN]: 	at java.lang.Thread.run(Thread.java:724)
[15:49:37] [Thread-27/WARN]: Caused by: java.net.NoRouteToHostException: Cannot assign requested address
[15:49:37] [Thread-27/WARN]: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
[15:49:37] [Thread-27/WARN]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
[15:49:37] [Thread-27/WARN]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
[15:49:37] [Thread-27/WARN]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
[15:49:37] [Thread-27/WARN]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[15:49:37] [Thread-27/WARN]: 	at java.net.Socket.connect(Socket.java:579)
[15:49:37] [Thread-27/WARN]: 	at java.net.Socket.connect(Socket.java:528)
[15:49:37] [Thread-27/WARN]: 	at java.net.Socket.<init>(Socket.java:425)
[15:49:37] [Thread-27/WARN]: 	at java.net.Socket.<init>(Socket.java:241)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:254)
[15:49:37] [Thread-27/WARN]: 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:292)
[15:49:37] [Thread-27/WARN]: 	... 17 more

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Ran without an error with iConomy for over 2 years now. Loaded the plugin up, and the errors started spamming. Disabled, and they stopped.

Specs:
iConomy v7.0
Vault v1.5.3-b37
Spigot 1.8 (not 1.8.3) - Updated to lasted 1.8 and tested; the problem still occurs.

**Comment by Puharesource** [comment]
TitleManager never directly talks to iConomy and all it does is get the player's balance.

iConomy has also been outdated for more than 3 years now and it's very much so NOT recommended to use it as it is know for causing issues, I'd suggest finding a still active economy plugin rather than iConomy.

**Comment by Matmorcat** [comment]
iConomy is still a very good plugin and works great with every other plugin. Never had a problem with it until we installed TitleManager.

So I guess this means you're not going to fix your plugin's problem.
(If it works without TitleManager, and breaks with TitleManager, that must mean the problem lies with TitleManager) :(

**Comment by Wundero** [comment]
I can guarantee that those errors have nothing to do with titlemanager. They instead are multiple plugins that are having trouble accessing your MySQL database, which TitleManager does not communicate with. If you actually read through the error logs, you would have seen multiple failures to connect to your database. This has nothing to do with this plugin.

**Comment by Puharesource** [comment]
I have a feeling that iConomy doesn't cache a player's money and instead opens a connection, which if his tabmenu is sending the balance 10 - 20 times a second, it will in turn congest the connection to the Database.

This feels entirely like an iConomy error as it should be cache'ing connected player's balance.

**Comment by Matmorcat** [comment]
Is it possible to get a version of TitleManager or better yet, a config option to disable the Vault hook? That would solve the problem and as far as I know, wouldn't be hard. A lot of plugins that use economy plugins have this in their configs too.

**Comment by Puharesource** [comment]
I can definitely see the plus sides of not caching them, however, running all of those queries could possibly cause waayyy bigger issues in the future.

Anyways, I've created a new issue that I'll have to look at sometime after all of the work I have to do for my exams.

You can find the issue here #32
