### ISSUE TITLE
Error with %{tps} placeholder

### ISSUE THREAD

**Issue by smirnovv2007** [Puharesource/TitleManager#310]
**Screenshots**
![image](https://user-images.githubusercontent.com/34893489/104838026-5f91e600-58c9-11eb-8b42-e27936a9400d.png)

**Stacktrace / Error**
```
[pool-14-thread-1/FATAL]: Thread pool-14-thread-1 failed thread check for reason: Asynchronous command dispatch
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:782) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:758) ~[patched_1.16.5.jar:git-Yatopia-"f8c5c21"]
	at io.puharesource.mc.titlemanager.internal.placeholder.PlaceholderTps.getOutput(PlaceholderTps.kt:11) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.placeholder.PlaceholderTps.getTps(PlaceholderTps.kt:17) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$12.invoke(PlaceholderServiceText.kt:62) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$12.invoke(PlaceholderServiceText.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$3.getText(PlaceholderServiceText.kt:190) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:144) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setHeader(PlayerListServiceSpigot.kt:74) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createHeaderSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:52) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createHeaderSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:22) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:83) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:90) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:10) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.task.SchedulerServiceAsync$scheduleRaw$1.run(SchedulerServiceAsync.kt:39) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Server information:**
 - TitleManager version: 2.3.1
 - Spigot version:  Yatopia 1.16.5

**Comment by Puharesource** [comment]
Should be fixed in a2496bd6ba686d65d1967cdf48fc3b2b9f6c7882
