### ISSUE TITLE
Nashorn Keeping the plugin from initializing

### ISSUE THREAD

**Issue by TheCiROMG** [Puharesource/TitleManager#350]
**Describe the bug**
```
[12:54:50 ERROR]: Error occurred while disabling TitleManager v2.3.1 (Is it up to date?)
io.puharesource.mc.titlemanager.shaded.kotlin.UninitializedPropertyAccessException: lateinit property titleManagerService has not been initialized
        at io.puharesource.mc.titlemanager.TitleManagerPlugin.onDisable(TitleManagerPlugin.kt:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[paper-1.16.5.jar:git-Paper-574]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[paper-1.16.5.jar:git-Paper-574]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[paper-1.16.5.jar:git-Paper-574]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[paper-1.16.5.jar:git-Paper-574]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[paper-1.16.5.jar:git-Paper-574]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[paper-1.16.5.jar:git-Paper-574]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

**To Reproduce**
1. Put latest version
2. Start the server
3. See the console

**Screenshots**
![image](https://user-images.githubusercontent.com/61605643/113018992-81280d00-9157-11eb-93a5-23cf67957154.png)

**Server information:**
 - TitleManager version: 2.2.3]
 - Paper : 1.16.5 574

**Comment by Puharesource** [comment]
I can see that there's an error above the one you sent as well + please upgrade to 2.3.3

**Comment by TheCiROMG** [comment]
although it is updated, it throws the same error

**Comment by Puharesource** [comment]
Strange, I'll try and figure things out
