### ISSUE TITLE
Error occurred while enabling TitleManager v2.3.3 (Is it up to date?)

### ISSUE THREAD

**Issue by cloakfox** [Puharesource/TitleManager#354]
```
[15:43:09] [Server thread/INFO]: [TitleManager] Enabling TitleManager v2.3.3
[15:43:09] [Server thread/ERROR]: Error occurred while enabling TitleManager v2.3.3 (Is it up to date?)
java.lang.NullPointerException: null
	at io.puharesource.mc.titlemanager.internal.config.TMConfigMain$hooks$2.invoke(TMConfig.kt:48) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.config.TMConfigMain$hooks$2.invoke(TMConfig.kt:34) ~[?:?]
	at io.puharesource.mc.titlemanager.shaded.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.config.TMConfigMain.getHooks(TMConfig.kt) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot.checkCombatLogXHook(ListenerServiceSpigot.kt:75) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot.registerListeners(ListenerServiceSpigot.kt:69) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.TitleManagerServiceSpigot.start(TitleManagerServiceSpigot.kt:33) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:36) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:581) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:283) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1057) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"8de8e82"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

Titlemanager doesnt want to load because of combatlogx

**Comment by cloakfox** [comment]
Tried with latest (stable) combatlogx 10.3.8.3 and get same error/issue.

**Comment by Puharesource** [comment]
Add
```yml
hooks:
  combatlogx: true
```

To your TitleManager config.yml. You can see how it should be here: https://github.com/Puharesource/TitleManager/blob/master/src/main/resources/config.yml

Ideally this should be automatically added to your config, when you updated to the latest version of TitleManager, but an error in the current build causes this to not happen. Sorry for the inconvenience.

**Comment by cloakfox** [comment]
Fixed, thanks for the swift response!

**Comment by Puharesource** [comment]
No problem :)
