### ISSUE TITLE
Whose problem is it and how to solve it

### ISSUE THREAD

**Issue by yuankun1** [Puharesource/TitleManager#372]
```
[19:10:20] [pool-94-thread-1/WARN]: [EliteMobs] Failed to get double value from database!
[19:10:20] [pool-94-thread-1/WARN]: java.sql.SQLException: ResultSet closed
[19:10:20] [pool-94-thread-1/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "com.magmaguy.elitemobs.playerdata.PlayerData.getDatabaseDouble(java.util.UUID, String)" is null
[19:10:20] [pool-94-thread-1/WARN]: 	at com.magmaguy.elitemobs.playerdata.PlayerData.getCurrency(PlayerData.java:51)
[19:10:20] [pool-94-thread-1/WARN]: 	at com.magmaguy.elitemobs.economy.EconomyHandler.checkCurrency(EconomyHandler.java:45)
[19:10:20] [pool-94-thread-1/WARN]: 	at com.magmaguy.elitemobs.thirdparty.placeholderapi.Placeholders.onPlaceholderRequest(Placeholders.java:115)
[19:10:20] [pool-94-thread-1/WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31)
[19:10:20] [pool-94-thread-1/WARN]: 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
[19:10:20] [pool-94-thread-1/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
[19:10:20] [pool-94-thread-1/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.placeholder.PlaceholderAPIHook.replacePlaceholders(Hooks.kt:18)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceTextFromHooks(PlaceholderServiceText.kt:171)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:158)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.setScoreboardValue(ScoreboardServiceSpigot.kt:137)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot$createScoreboardValueSendableAnimation$4.invoke(ScoreboardServiceSpigot.kt:222)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot$createScoreboardValueSendableAnimation$4.invoke(ScoreboardServiceSpigot.kt:33)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:97)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation$update$2.invoke(PartBasedSendableAnimation.kt:10)
[19:10:20] [pool-94-thread-1/WARN]: 	at io.puharesource.mc.titlemanager.internal.services.task.SchedulerServiceAsync$scheduleRaw$1.run(SchedulerServiceAsync.kt:44)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[19:10:20] [pool-94-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Puharesource** [comment]
It's EliteMob's issue
