### ISSUE TITLE
Won't work with KCauldron 1.7.10

### ISSUE THREAD

**Issue by Wolftein** [Puharesource/TitleManager#40]
```
[18:09:24 INFO]: [TitleManager] Enabling TitleManager v1.5.9
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/ChatComponentText
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:20)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:21)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/EntityPlayer
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:23)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PlayerConnection
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:24)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/Packet
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:25)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:60)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:26)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 WARN]: java.lang.ClassNotFoundException: org/spigotmc/ProtocolInjector
[18:09:24 WARN]:        at java.lang.Class.forName0(Native Method)
[18:09:24 WARN]:        at java.lang.Class.forName(Class.java:264)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:13)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:66)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:28)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22)
[18:09:24 WARN]:        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[18:09:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[18:09:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[18:09:24 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[18:09:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[18:09:24 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[18:09:24 WARN]:        at java.lang.Thread.run(Thread.java:745)
[18:09:24 ERROR]: Error occurred while enabling TitleManager v1.5.9 (Is it up to date?)
java.lang.NullPointerException
        at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManagerProtocolHack1718.<init>(ReflectionManagerProtocolHack1718.java:29) ~[?:?]
        at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:22) ~[?:?]
        at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1481.144]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1481.144]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1481.144]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1481.144]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1481.144]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Puharesource** [comment]
I've never really used Cauldron and I don't know too much about it.

Is the version of Cauldron you're using a direct fork off of Spigot's 1.7-1.8 ProtocolHack? if so, be sure that you're using a proper version of ProtocolHack (specifically 1649).

If this isn't the case, then I don't believe that I will be able to make this for you.

**Comment by Wolftein** [comment]
I have ask and KCauldron don't use ProtocolHack. I'll wait for KCauldron to update. Thanks :)
