### ISSUE TITLE
Compatible with 1.18.1 or an Error and Bug?

### ISSUE THREAD

**Issue by Futodama** [Puharesource/TitleManager#421]
**Describe the bug**
Hi! Your plugin has stopped working on 1.18.1 servers. Most likely compatibility is needed. I started the problem as a "Bug" out of consideration that this could be caused by a wrong interpretation. Only TAB works on the server, but the sidebar stubbornly refuses to work, I tried everything.

**To Reproduce**
Just start the server and log in to it.

**Stacktrace / Error**
[15:53:01 ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.3.4
java.util.NoSuchElementException: Array contains no element matching the predicate.
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitleWithoutLimit(ScoreboardHandler.kt:110) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitle(ScoreboardHandler.kt:35) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:42) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:15) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveScoreboard(ScoreboardServiceSpigot.kt:61) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveDefaultScoreboard(ScoreboardServiceSpigot.kt:68) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.toggleScoreboardInWorld(ScoreboardServiceSpigot.kt:234) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[TitleManager-2.3.4.jar:?]
        at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[TitleManager-2.3.4.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-68]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:307) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Server information:**
 - TitleManager v2.3.4
 - Paper 1.18.1

**Comment by Rothes** [comment]
This is fixed in https://github.com/Puharesource/TitleManager/pull/412
You can clone and compile this project if you need it now

**Comment by Futodama** [comment]
I don't know how this is done. I'm not a developer...

**Comment by Tsoccerguy3** [comment]
[TitleManager-2.3.5-all.jar.zip](https://github.com/Puharesource/TitleManager/files/7708299/TitleManager-2.3.5-all.jar.zip)

**Comment by Futodama** [comment]
Thank you very much!

**Comment by M4RC0Sx** [comment]
> [TitleManager-2.3.5-all.jar.zip](https://github.com/Puharesource/TitleManager/files/7708299/TitleManager-2.3.5-all.jar.zip) compiled from source 1.18.1

How did you make it work? I am trying to compile and having the following error with dependencies, I have updated everything and don't know exactly what to do:
`Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.6.0'] was not found in any of the following sources:`

**Comment by Tsoccerguy3** [comment]
After that security issue a few days ago , anything java related got patches and version changes . The directories this plugin are gone . and some directories for security reasons are now blocked . The day after the panic , most of my software could not complete either. I had to hunt down locations for working directories . This developer is using some sort of BOT to resolve the dependencies and push them to the git . This will not work . Until the Dev notices the software is broken this source is not going to compile.

**Comment by Tsoccerguy3** [comment]
LOL , this may be the only copy in existence for 1.18.1
