### ISSUE TITLE
PlayerJoinEvent Error

### ISSUE THREAD

**Issue by fasoessp** [Puharesource/TitleManager#428]
When a player enters the server, an error report will appear in the TitleManager

Error report when the player joins the server: https://pastebin.com/AmYCHRYW

Error reports also appear when using commands
link: https://pastebin.com/6sQeEaLY

**Comment by fasoessp** [comment]
I found that when I use %{ping} this variable, it will cause a plug-in error

**Comment by ArtelGG** [comment]
You can work around this right now by using a PAPI placeholder for the player's ping.

**Comment by molor** [comment]
Can confirm the same problem on Paper build 81 :c

**Comment by molor** [comment]
```
[2021-12-18 18:45:21 | Server thread] Could not pass event PlayerJoinEvent to TitleManager v2.3.5
java.lang.ExceptionInInitializerError: null
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$1.getText(PlaceholderServiceText.kt:183) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:152) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setFooter(PlayerListServiceSpigot.kt:156) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:101) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:100) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:60) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedFooter(PlayerListServiceSpigot.kt:171) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedHeaderAndFooter(PlayerListServiceSpigot.kt:198) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-81]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:307) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.network.NetworkManager.a(NetworkManager.java:526) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchFieldException: playerConnection
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.reflections.ReflectionClass.getField(ReflectionClass.kt:29) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.reflections.EntityPlayer.<init>(Classes.kt:25) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.reflections.ReflectionPlayerExtensionsKt.<clinit>(ReflectionPlayerExtensions.kt:6) ~[?:?]
	... 28 more
```

**Comment by Puharesource** [comment]
Thanks for the stacktrace, should be an easy fix
