### ISSUE TITLE
Could not pass event PlayerJoinEvent to TitleManager v2.3.6

### ISSUE THREAD

**Issue by leoncp9** [Puharesource/TitleManager#431]
https://pastebin.com/0Gdr4cCX
paper 1.18.1

**Comment by molor** [comment]
Yeah, same problem but new field name.. @Puharesource 

```
[11:11:59] Could not pass event PlayerJoinEvent to TitleManager v2.3.6
java.lang.ExceptionInInitializerError: null
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$1.getText(PlaceholderServiceText.kt:183) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:152) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setFooter(PlayerListServiceSpigot.kt:156) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:101) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:100) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:60) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedFooter(PlayerListServiceSpigot.kt:171) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedHeaderAndFooter(PlayerListServiceSpigot.kt:198) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[?:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:307) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:526) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:201) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchFieldException: networkManager
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.ReflectionClass.getField(ReflectionClass.kt:29) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.PlayerConnection.<init>(Classes.kt:33) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.ReflectionPlayerExtensionsKt.<clinit>(ReflectionPlayerExtensions.kt:7) ~[?:?]
        ... 28 more
```

**Comment by FunkyNico** [comment]
Hello guys, same here on paper 1.18.1 build 108.

https://mclo.gs/VsWSbjN

**Comment by AntZaro** [comment]
I'm having the same error message. Running on 1.18.2. I commented on a more recent post, but then I saw this issue was already reported here.

https://pastebin.com/mg35CE9t

**Comment by YuiOfAstora** [comment]
Same problem in 1.17.1 ,as long as I add the %{ping} placeholder.
```
[03:28:07] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.3.6
java.lang.ExceptionInInitializerError: null
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$1.getText(PlaceholderServiceText.kt:183) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:152) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setFooter(PlayerListServiceSpigot.kt:156) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:101) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:100) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:60) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedFooter(PlayerListServiceSpigot.kt:171) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedHeaderAndFooter(PlayerListServiceSpigot.kt:198) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.players.PlayerList.a(PlayerList.java:276) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1336) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchFieldException: networkManager
        at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.ReflectionClass.getField(ReflectionClass.kt:29) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.PlayerConnection.<init>(Classes.kt:33) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.ReflectionPlayerExtensionsKt.<clinit>(ReflectionPlayerExtensions.kt:7) ~[?:?]
```

**Comment by Stormbow** [comment]
Same error in Minecraft 1.19.x.

https://pastebin.com/PKATVMPD

**Comment by SladeGit** [comment]
1.19 not work, pls fix, its the best plugin :(

**Comment by ilkeEren27** [comment]
I have the same issue, please fix it it's really the best tab & scoreboard plugin.

**Comment by Wu-jiyan** [comment]
the same on 1.20.1 please fix it!
thx
