### ISSUE TITLE
PlayerJoinEvent & SB Error

### ISSUE THREAD

**Issue by Hugytor09YT** [Puharesource/TitleManager#437]
**Describe the bug**
The scorebaord dont work properly.

**To Reproduce**
1. Install the plugin (Spigot Lastet) in Paper 1.16.5
2. See error

**Expected behavior**
The ScoreBoard dont work.

**Screenshots**
None

**Stacktrace / Error**
[Server thread/ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.3.6
java.lang.ExceptionInInitializerError: null
        at io.puharesource.mc.titlemanager.internal.reflections.NMSManager.getClassProvider(NMSManager.kt:61) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitleWithoutLimit(ScoreboardHandler.kt:106) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.setTitle(ScoreboardHandler.kt:36) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:43) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.scoreboard.ScoreboardHandler.<init>(ScoreboardHandler.kt:16) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveScoreboard(ScoreboardServiceSpigot.kt:61) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.giveDefaultScoreboard(ScoreboardServiceSpigot.kt:68) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.features.ScoreboardServiceSpigot.toggleScoreboardInWorld(ScoreboardServiceSpigot.kt:234) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetScoreboard$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.PlayerList.a(PlayerList.java:267) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.LoginListener.c(LoginListener.java:173) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.LoginListener.tick(LoginListener.java:71) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:229) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:143) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1246) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:394) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.ChatComponentText
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[server.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.ReflectionClass.<init>(ReflectionClass.kt:7) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.NMSType.getReflectionClass(NMSType.kt:16) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.NMSClassProvider.associate(NMSClassProvider.kt:12) ~[?:?]
        at io.puharesource.mc.titlemanager.internal.reflections.Provider117.<clinit>(Providers.kt:203) ~[?:?]
        ... 25 more

**Server information:**
 - TitleManager version: [Example:. 2.1.5]
 - Spigot version: [Example: Spigot 1.14.4 or PaperSpigot 1.12]

**Additional context**

**Comment by MrPranklez** [comment]
Also happens with the latest build of Purpur with 1.18

**Comment by MineSAT** [comment]
Describe the bug
The plugin dont work properly.

To Reproduce
Steps to reproduce the behavior:

Install the plugin (Spigot Lastet) in Paper 1.18.1
See error
Expected behavior
The ScoreBoard, Titles and Tab dont work.

Screenshots
None

Stacktrace / Error
[00:46:51 ERROR]: Could not pass event PlayerJoinEvent to TitleManager v2.3.5
java.lang.ExceptionInInitializerError: null
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$loadBuiltinPlaceholders$11.invoke(PlaceholderServiceText.kt:63) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText$createPlaceholder$1.getText(PlaceholderServiceText.kt:183) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.placeholder.PlaceholderServiceText.replaceText(PlaceholderServiceText.kt:152) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setFooter(PlayerListServiceSpigot.kt:156) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:101) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot$createFooterSendableAnimation$4.invoke(PlayerListServiceSpigot.kt:100) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.update(PartBasedSendableAnimation.kt:90) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.model.animation.PartBasedSendableAnimation.start(PartBasedSendableAnimation.kt:60) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedFooter(PlayerListServiceSpigot.kt:171) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.features.PlayerListServiceSpigot.setProcessedHeaderAndFooter(PlayerListServiceSpigot.kt:198) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:212) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.services.event.ListenerServiceSpigot$registerSetHeaderAndFooter$$inlined$listenEventSync$default$1.invoke(ListenerServiceSpigot.kt:95) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.model.event.TMEventListener._init_$lambda-1(TMEventListener.kt:31) ~[TitleManager-2.3.5.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:308) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchFieldException: playerConnection
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at io.puharesource.mc.titlemanager.internal.reflections.ReflectionClass.getField(ReflectionClass.kt:29) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.reflections.EntityPlayer.<init>(Classes.kt:25) ~[TitleManager-2.3.5.jar:?]
	at io.puharesource.mc.titlemanager.internal.reflections.ReflectionPlayerExtensionsKt.<clinit>(ReflectionPlayerExtensions.kt:6) ~[TitleManager-2.3.5.jar:?]
	... 28 more


Server information:

TitleManager version: 2.3.5 and 2.3.6
Spigot version: Paper 1.18.1

**Comment by precompile** [comment]
Same here on 1.18.1 with v2.3.6

**Comment by dandykong** [comment]
Still happening on Paper 1.19.4 with 2.3.6.

**Comment by retex07** [comment]
Still happening on Paper 1.16.5 with 2.3.6, but not happening on Paper 1.12.2 with 2.3.6...

**Comment by retex07** [comment]
For anyone who has a similar error, here is the solution:
1) Decompile "SmsManager" in the package "io.puharesource.mc.title manager.internal.reflections".
2) In the "static" block, add several versions to the "Supported versions" if they are not there.
3) In the "static" block, replace the string "String var2 = version.string(lastIndexOf Default((CharSequence)version, ".", 0, false, 6, (Object)null) + 1)" to this one: "String var2 = transformString(version)".
4) In the same class, add the "transformString" method:
 ```
public static String transform String(String input) {
        int lastIndexOf Dot = input.lastIndexOf(".");
        if (lastIndexOf Dot != -1) {
            return input.substring(lastIndexOfDot + 1);
        }
        return input;
    }
```

This is the easiest way to solve this problem. It didn't work for me on version 1.16.5 (1_16_R3). After these changes, everything worked. The "version" variable stores a string of the form: "org.bukkit.craftbukkit.v1_16_R3", and the "transformString" method allows you to convert this string to what we need.

The most important thing is to compile in the JDK 16 version (as low as possible), as problems arise with higher versions.
