### ISSUE TITLE
Title Manager 1.5.11 won't load

### ISSUE THREAD

**Issue by VincentVerdynanta** [Puharesource/TitleManager#67]
It outputs this on the console:
```java
14.12 10:35:55 [Server] INFO ... 18 more
14.12 10:35:55 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
14.12 10:35:55 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
14.12 10:35:55 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:247)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:212)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:304)
14.12 10:35:55 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
14.12 10:35:55 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:34)
14.12 10:35:55 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
14.12 10:35:55 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source)
14.12 10:35:55 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
14.12 10:35:55 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source)
14.12 10:35:55 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source)
14.12 10:35:55 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source)
14.12 10:35:55 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source)
14.12 10:35:55 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source)
14.12 10:35:55 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source)
14.12 10:35:55 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method)
14.12 10:35:55 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
14.12 10:35:55 [Server] WARNING Error enabling plugin TitleManager
```

If the problem is with the java version, then I can't do nothing. Because I'm just using a hosting.

**Comment by Puharesource** [comment]
Have you been using /reload? Because this message looks like Bukkit isn't even loading, which is quite impossible... However, this type of issue could very rarely happen if you reload the server often.

Try to restart your server and see if it fixes it.

**Comment by VincentVerdynanta** [comment]
Oh.. This is Bukkit plugin? I thought it was BungeeCord plugin

**Comment by Puharesource** [comment]
Yup, haha
