### ISSUE TITLE
Crazy spam

### ISSUE THREAD

**Issue by 7h3ev1l** [Puharesource/TitleManager#77]
`[02:00:40 WARN]: Could not pass incoming plugin message to TitleManager v1.5.11
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:449) ~[patched_1.9.2.jar:git-Paper-712]
        at io.puharesource.mc.titlemanager.backend.bungee.BungeeManager.onPluginMessageReceived(BungeeManager.java:87) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:2543) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.PacketPlayInCustomPayload.a(SourceFile:58) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.PacketPlayInCustomPayload.a(SourceFile:8) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-712]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:811) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-712]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-712]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340) ~[?:1.8.0_77]
        at java.io.DataInputStream.readUTF(DataInputStream.java:589) ~[?:1.8.0_77]
        at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_77]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readUTF(ByteStreams.java:447) ~[patched_1.9.2.jar:git-Paper-712]
        ... 14 more
 `
I get this spam.. its not stoping. The plugin is working but i get this spam.

**Comment by Puharesource** [comment]
#62
