### ISSUE TITLE
Needs update for 1.10

### ISSUE THREAD

**Issue by SmallSansSerif** [Puharesource/TitleManager#78]
[01:19:18] [Server thread/INFO]: [TitleManager] Enabling TitleManager v1.6.0
[01:19:18] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.ChatComponentText
[01:19:18] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92)
[01:19:18] [Server thread/WARN]:     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[01:19:18] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[01:19:18] [Server thread/WARN]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[01:19:18] [Server thread/WARN]:     at java.lang.Class.forName0(Native Method)
[01:19:18] [Server thread/WARN]:     at java.lang.Class.forName(Unknown Source)
[01:19:18] [Server thread/WARN]:     at io.puharesource.mc.titlemanager.backend.reflections.ReflectionClass.<init>(ReflectionClass.java:14)
[01:19:18] [Server thread/WARN]:     at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager$ReflectionType.getReflectionClass(ReflectionManager.java:61)
[01:19:18] [Server thread/WARN]:     at io.puharesource.mc.titlemanager.backend.reflections.managers.ReflectionManager183.<init>(ReflectionManager183.java:19)
[01:19:18] [Server thread/WARN]:     at io.puharesource.mc.titlemanager.backend.reflections.ReflectionManager.createManager(ReflectionManager.java:24)
[01:19:18] [Server thread/WARN]:     at io.puharesource.mc.titlemanager.TitleManager.onEnable(TitleManager.java:51)
[01:19:18] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[01:19:18] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319)
[01:19:18] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[01:19:18] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358)
[01:19:18] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318)
[01:19:18] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414)
[01:19:18] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379)
[01:19:18] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333)
[01:19:18] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274)
[01:19:18] [Server thread/WARN]:     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580)
[01:19:18] [Server thread/WARN]:     at java.lang.Thread.run(Unknown Source)

**Comment by Puharesource** [comment]
Thanks for letting me know, I'm working on an update right now. :)
